/* 
 * File:   corpo.c
 * Author: blastin
 *
 * Created on 23 de Outubro de 201BM, 22:16
 */



#include "header.h"

create_object_m(mapa02) = { 
 "nome",
  
  {
      {BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},    
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,BM},
      {BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM,BM},
  }
    
    
};
